app:
  name: springboot_demo
  description: ${app.name} is a Spring Boot application

spring:
  application:
    name: springboot_demo

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer.group-id: myGroup

  profiles:
    active: dev

  jackson:
    date-format: YYYY-MM-DD
    joda-date-time-format: YYYY-MM-DD HH:mm:ss

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml #mapper xml 文件地址
  type-aliases-package: com.silverdawn.domain #实体类包路径
  check-config-location: true
  config-location: classpath:mybatis-config.xml #检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml

logging:
  config: classpath:logback-spring.xml

server:
  port: 8080
  session:
    timeout: 1800
  connection-timeout:  60000
  context-path: /springboot_demo

---
spring:
   profiles: dev
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/qiuqiu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
     username: root
     password: 123456
     type:  com.alibaba.druid.pool.DruidDataSource
     druid:
       filters: config
       maxActive: 50
       initialSize: 10
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       connectionProperties:

---
spring:
   profiles: test
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/qiuqiu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
     username: root
     password: 123456
     type:  com.alibaba.druid.pool.DruidDataSource
     druid:
       filters: config
       maxActive: 50
       initialSize: 10
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       connectionProperties:
